name = "tailwind"
version = "0.1.0"
gleam = ">= 0.32.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"
simplifile = "~> 1.0"
tom = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.10"
