name = "tailwind"
version = "0.1.0"
gleam = ">= 0.32.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_httpc = "~> 2.1"
gleam_http = "~> 3.5"
simplifile = "~> 1.0"
tom = "~> 0.2"
gleam_erlang = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 0.10"

[tailwind]
version = "3.3.5"
args = [
  "--config=tailwind.config.js",
  "--input=./test/input.css",
  "--output=./priv/output.css",
]
