name = "glailglind"
version = "2.0.0"
gleam = ">= 0.34.0"

description = "Gleam modules and functions for installing and invoking TailwindCSS"
licences = ["Apache-2.0"]
repository = { type = "github", user = "okkdev", repo = "glailglind" }

[dependencies]
gleam_stdlib = ">= 0.55.0 and < 2.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 1.1.1 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"

[tailwind]
version = "4.0.8"
args = ["-i=./test/input.css", "-o=./build/css/output.css"]
